# Generated by Django 3.2.18 on 2023-04-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=80)),
                ('number_of_pages', models.IntegerField()),
                ('category', models.CharField(max_length=80)),
                ('about', models.TextField()),
                ('rating', models.IntegerField(choices=[(0, 'Very bad'), (1, 'Bad'), (2, 'Ok'), (3, 'Good'), (4, 'Very good')], default=2)),
                ('data_started_reading', models.DateField()),
                ('date_finished_reading', models.DateField()),
                ('isbn', models.IntegerField(unique=True)),
            ],
        ),
    ]
