# Generated by Django 3.2.18 on 2023-04-13 13:00

from django.db import migrations, models
import django.utils.timezone
from blog.models import Book


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
