# Generated by Django 3.2.18 on 2023-04-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20230417_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='image_url',
        ),
    ]
