# Generated by Django 3.2.18 on 2023-04-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20230420_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.AlterField(
            model_name='book',
            name='data_started_reading',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_finished_reading',
            field=models.DateField(blank=True),
        ),
    ]
