# Generated by Django 3.2.18 on 2023-04-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20230421_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='data_started_reading',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_finished_reading',
            field=models.DateTimeField(),
        ),
    ]
