# Generated by Django 3.2.18 on 2023-04-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20230421_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.IntegerField(choices=[(0, 'Read'), (1, 'Currently Reading'), (2, 'Want to Read'), (3, 'Abandoned')], default=0),
        ),
    ]
