# Generated by Django 3.2.18 on 2023-04-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(choices=[(0, 'unread'), (1, 'Very bad'), (2, 'Bad'), (3, 'Ok'), (4, 'Good'), (5, 'Very good')], default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.IntegerField(choices=[(0, 'Read'), (1, 'Currently Reading'), (2, 'Want to Read'), (3, 'Abandoned')], default=2),
        ),
    ]
